REM Create DB
@PAUSE
SqlCmd -E -S LOCALHOST -Q "CREATE DATABASE [42.Board]"

REM Restore DB
@PAUSE
SqlCmd -E -S LOCALHOST -Q "RESTORE DATABASE [42.Board] FROM DISK='%~dp042.Board.bak' WITH REPLACE"
@PAUSE
